version: '3'

services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
