apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jenkins-ns
  name: jenkins-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi